version: '3.8'
services:
  movies:
    image: moulashaik9618/paytmtrain:latest
    ports:
      - "8081:80"
    deploy:
      replicas: 3
  train:
    image: moulashaik9618/paytmrecharge:latest
    ports:
      - "8082:80"
    deploy:
      replicas: 3
  recharge:
    image: moulashaik9618/paytmmovie:latest
    ports:
      - "8083:80"
    deploy:
      replicas: 3
