version: '3.8'
services:
  movies:
    image: moulashaik9618/paytmmovies:V1
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: moulashaik9618/paytmtrain:V1
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: moulashaik9618/paytmrecharge:V1
    ports:
      - "83:80"
    deploy:
      replicas: 3
